# 工作流名称
name: Build and Deploy React Project
# 工作流运行时显示名称
run-name: ${{ github.actor }} is building and deploying the React project.
# 怎样触发工作流
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# 工作流程任务（通常含有一个或多个步骤）
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout private GitLab repository
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git clone -b dev --single-branch --depth 1 https://oauth2:${GITLAB_TOKEN}@git.wsc.tech/AFZJ/rust-red-web.git rust-red-web
          cd rust-red-web
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Or your desired Node.js version
      - name: Install Dependencies
        working-directory: ./rust-red-web # Specify the working directory
        run: yarn install
      - name: Build Project
        working-directory: ./rust-red-web # Specify the working directory
        run: yarn build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@wsc.tech -p 30006 << EOF
            # Assuming you have a directory for your web app, e.g., /home/nginx/webroot/afzj-frontend
            # Create a timestamped backup directory
            mkdir -p /home/nginx/webroot/afzj-frontend/backups
            TIMESTAMP=$(date +%Y%m%d%H%M%S)
            BACKUP_DIR="/home/nginx/webroot/afzj-frontend/backups/\$TIMESTAMP"
            mkdir \$BACKUP_DIR

            # Copy current files to backup (if directory exists)
            if [ -d "/home/nginx/webroot/afzj-frontend/current" ]; then
              cp -r /home/nginx/webroot/afzj-frontend/current/* \$BACKUP_DIR
            fi
            
            # Create or clear the current directory
            rm -rf /home/nginx/webroot/afzj-frontend/current
            mkdir -p /home/nginx/webroot/afzj-frontend/current

            # Copy the new build to the server
            exit # Exit the here-doc to use scp locally
          EOF
          scp -o StrictHostKeyChecking=no -P 30006 -r ./build ubuntu@wsc.tech:/home/nginx/webroot/afzj-frontend/current # Correct path to build directory
          ssh -o StrictHostKeyChecking=no ubuntu@wsc.tech -p 30006 << EOF
            echo "Deployment completed."
          EOF
