# 工作流名称
name: Build YMPortal Project
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Build YMPortal Project Docker Image.
# 怎样触发工作流
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# 工作流程任务（通常含有一个或多个步骤）
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout private GitLab repository
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git clone --depth 1 https://oauth2:${GITLAB_TOKEN}@git.wsc.tech/yangf/ym_portal.git ./
      - name: Login to Aliyun Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}
          logout: false
      - name: Deploy
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/gskj/ym_portal:latest
          labels: ym_portal