# 工作流名称
name: Build Sui Develop Environment Docker Image
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Build Sui Develop Environment Docker Image.
# 怎样触发工作流
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# 工作流程任务（通常含有一个或多个步骤）
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout private GitLab repository
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      run: |
        git clone https://git.wsc.tech/yangf/ym_portal.git ym_portal
        cd ym_portal
      - name: Deploy
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: master
          labels: ym_portal