# 工作流名称
name: Build Rauthy Env
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Build Rauthy Env Docker Image.
# 怎样触发工作流
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# 工作流程任务（通常含有一个或多个步骤）
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Aliyun Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.DOCKERUSERNAME }}
        password: ${{ secrets.DOCKERPASSWORD }}
        logout: false
    - uses: actions/checkout@v4
    - name: Build the Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64
        push: true
        tags: registry.cn-hangzhou.aliyuncs.com/gskj/rauthy-dev:latest
        labels: rauthy-dev