# 工作流名称
name: Build YMPortal Project
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Build YMPortal Project Docker Image.
# 怎样触发工作流
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# 工作流程任务（通常含有一个或多个步骤）
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout private GitLab repository
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git clone --depth 1 https://oauth2:${GITLAB_TOKEN}@git.wsc.tech/yangf/ym_portal.git ym_portal
          cd ym_portal
      - name: Login to Aliyun Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}
          logout: false
      - name: build image
        uses: docker/build-push-action@v3
        with:
          context: ./ym_portal
          file: ym_portal/Dockerfile
          platforms: linux/amd64
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/gskj/ym_portal:latest
          labels: ym_portal
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.YM_SSH_PRIVATE_KEY }}
      - name: Run commands on remote server
        run: |
          ssh -o StrictHostKeyChecking=no root@38.54.119.93:22222 '
            docker pull registry.cn-hangzhou.aliyuncs.com/gskj/ym_portal:latest;
            docker stop ym_portal || true;
            docker rm ym_portal || true;
            docker run --name ym_portal -i -t -d -p 3001:3000 -v /home/ym-portal-server/db:/app/db -v /root/nginx/webroot/ym_upload:/app/public/upload -v /etc/localtime:/etc/localtime:ro -e TZ=Asia/Shanghai registry.cn-hangzhou.aliyuncs.com/gskj/ym_portal:latest;
            docker images -a | grep ym_portal | awk '{print $3}' | xargs -r docker rmi || true;
          '
