name: Build and Push Cas builder
permissions:
  contents: read
  packages: write
on:
  workflow_dispatch:
  push:
    paths:
      - "Dockerfile.cas.client"
      - ".github/workflows/cas-client-builder.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.cas.builder
          platforms: linux/amd64
          push: true
          # 传递构建参数
          # build-args: |
          #   INSTALL_LIBREOFFICE=${{ matrix.lo }}
          #   INSTALL_FFMPEG=${{ matrix.ffmpeg }}
          # 动态打标签，例如 rust-red-runtime-base:full, rust-red-runtime-base:lite
          tags: |
            ghcr.io/wsc-studio/cas-builder-demo:latest
            ghcr.io/wsc-studio/cas-builder-demo:${{ github.sha }}
          labels: cas-builder-demo
