name: Build KZPIPE next-rust Project
run-name: ${{ github.actor }} is Building KZPIPE next-rust Project
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/rust-red-kzpipe-next.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout private GitLab repository
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        # dev-shared-ptr 分支
        run: |
          # 配置 git 凭证替换，确保子模块也能通过 token 拉取
          git config --global url."https://oauth2:${GITLAB_TOKEN}@git.wsc.tech/".insteadOf "https://git.wsc.tech/"
          git clone -b master --recursive --single-branch --depth 1 https://git.wsc.tech/kzpipe/rust-kzpipe-api.git rust-red
          cd rust-red
      # 登录Aliyun Docker Hub，用于push镜像
      - name: Login to Aliyun Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}
          logout: false

      # 登录 GHCR 以获取 builder 镜像
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build image
        uses: docker/build-push-action@v6
        with:
          context: ./rust-red
          file: rust-red/Dockerfile
          platforms: linux/amd64
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/gskj/rust-kzpipe-api:latest
          labels: rust-kzpipe-api
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Setup SSH
  #       uses: webfactory/ssh-agent@v0.9.1
  #       with:
  #         ssh-private-key: ${{ secrets.PROD_SSH_PRIVATE_KEY || secrets.DEV_SSH_PRIVATE_KEY }}
  #     - name: Run commands on remote server
  #       # 部署shared版本的rust-red
  #       # 宿主机端口号7026，映射容器端口号8080（api）
  #       # 宿主机端口号6669，映射容器端口号6669（tokio-console）
  #       # 通过 ENABLE_CONSOLE 环境变量来启用tokio-console的功能
  #       run: |
  #         ssh -o StrictHostKeyChecking=no root@git.wsc.tech -p 22 << 'EOF'
  #           docker pull registry.cn-hangzhou.aliyuncs.com/gskj/rust-red-shared:latest
  #           docker stop rust-iot-shared || true
  #           docker rm rust-iot-shared || true
            
  #           docker run -itd --name rust-iot-shared --privileged=true \
  #               -p 7026:8080 \
  #               -p 6669:6669 \
  #               -v /etc/localtime:/etc/localtime:ro \
  #               -v /root/home/rust-iot/config:/app/config \
  #               -v /root/home/rust-iot/data:/app/data \
  #               -v /root/home/rust-iot/flow:/app/flow \
  #               -v /root/home/nginx/webroot/iot-upload-image:/app/upload-image \
  #               -e TZ=Asia/Shanghai \
  #               -e ENABLE_CONSOLE=true \
  #               --log-opt max-size=500m \
  #               --log-opt max-file=3 \
  #               registry.cn-hangzhou.aliyuncs.com/gskj/rust-red-shared:latest
                
  #           docker images -a | grep rust-red-shared | awk '{print $3}' | xargs -r docker rmi || true
  #         EOF
