name: Deploy IOT Rust-Red Project [LITE] --- [FAST]
run-name: ${{ github.actor }} is Build Rust-Red Project Docker Image --- [FAST].
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.PROD_SSH_PRIVATE_KEY || secrets.DEV_SSH_PRIVATE_KEY }}
      - name: Run commands on remote server
        run: |
          ssh -o StrictHostKeyChecking=no root@git.wsc.tech -p 22 << 'EOF'
            docker pull registry.cn-hangzhou.aliyuncs.com/gskj/rust-red:latest
            docker stop rust-iot || true
            docker rm rust-iot || true
            
            docker run -itd --name rust-iot --privileged=true \
                -p 7024:8080 -p 6669:6669 \
                -v /etc/localtime:/etc/localtime:ro \
                -v /root/home/rust-iot/config:/app/config \
                -v /root/home/rust-iot/data:/app/data \
                -v /root/home/rust-iot/flow:/app/flow \
                -v /root/home/nginx/webroot/iot-upload-image:/app/upload-image \
                -e TZ=Asia/Shanghai \
                --log-opt max-size=500m \
                --log-opt max-file=3 \
                registry.cn-hangzhou.aliyuncs.com/gskj/rust-red:latest
                
            docker images -a | grep rust-red | awk '{print $3}' | xargs -r docker rmi || true
          EOF
