# 工作流名称
name: Build Rust-Red Project
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Build Rust-Red Project Docker Image.
# 怎样触发工作流
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# 工作流程任务（通常含有一个或多个步骤）
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout private GitLab repository
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git clone -b dev --single-branch --depth 1 https://oauth2:${GITLAB_TOKEN}@git.wsc.tech/base/rust-red-group/rust-red.git rust-red
          cd rust-red
      - name: Login to Aliyun Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}
          logout: false
      - name: build image
        uses: docker/build-push-action@v3
        with:
          context: ./rust-red
          file: rust-red/Dockerfile
          platforms: linux/amd64
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/gskj/rust-red:latest
          labels: rust-red
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
      - name: Run commands on remote server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@wsc.tech -p 30006 << 'EOF'
            docker pull registry.cn-hangzhou.aliyuncs.com/gskj/rust-red:latest
            docker stop rust-red-core || true
            docker rm rust-red-core || true
            docker stop rust-afzj-core || true
            docker rm rust-afzj-core || true
            docker stop rust-record-core || true
            docker rm rust-record-core || true
            docker run -itd --name rust-red-core -p 7024:8080 -v /etc/localtime:/etc/localtime:ro -v /home/rust-red-core/config:/app/config -v /home/rust-red-core/data:/app/data -v /home/rust-red-core/flow:/app/flow -v /home/rust-afzj/upload-image:/app/upload-image -e TZ=Asia/Shanghai registry.cn-hangzhou.aliyuncs.com/gskj/rust-red:latest
            docker run -itd --name rust-afzj-core -p 7025:8080 -v /etc/localtime:/etc/localtime:ro -v /home/rust-afzj/config:/app/config -v /home/rust-afzj/data:/app/data -v /home/rust-afzj/flow:/app/flow -v /home/rust-afzj/upload-image:/app/upload-image -e TZ=Asia/Shanghai registry.cn-hangzhou.aliyuncs.com/gskj/rust-red:latest
            docker run -itd --name rust-afzj-core \
                -p 7026:8080 \
                -v /etc/localtime:/etc/localtime:ro \
                -v /home/rust-record/config:/app/config \
                -v /home/rust-record/data:/app/data \
                -v /home/rust-record/flow:/app/flow \
                -v /home/nginx/webroot/record-frontend/upload-image:/app/upload-image \
                -e TZ=Asia/Shanghai \
                registry.cn-hangzhou.aliyuncs.com/gskj/rust-red:latest
            docker images -a | grep rust-red | awk '{print $3}' | xargs -r docker rmi || true
          EOF
