# 工作流名称
name: Build Rust-Red Project
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Build Rust-Red Project Docker Image.
# 怎样触发工作流
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# 工作流程任务（通常含有一个或多个步骤）
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout private GitLab repository
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git clone -b docker --single-branch --depth 1 https://oauth2:${GITLAB_TOKEN}@git.wsc.tech/base/rust-red-group/rust-red.git rust-red
          cd ym_portal
      - name: Login to Aliyun Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}
          logout: false
      - name: build image
        uses: docker/build-push-action@v3
        with:
          context: ./rust-red
          file: rust-red/Dockerfile
          platforms: linux/amd64
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/gskj/rust-red:latest
          labels: rust-red
