name: Build and Push Rust-Red Runtime Base
run-name: ${{ github.actor }} is Building Rust-Red Runtime Base Docker Image.
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: Checkout private GitLab repository
      #   env:
      #     GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      #   run: |
      #     git clone -b dev-shared-ptr --single-branch --depth 1 https://oauth2:${GITLAB_TOKEN}@git.wsc.tech/base/rust-red-group/rust-red.git rust-red
      #     cd rust-red
      - name: Login to Aliyun Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}
          logout: false
      - name: build image
        uses: docker/build-push-action@v6
        with:
          context: .
          # context: ./rust-red
          file: Dockerfile.runtime.base
          platforms: linux/amd64
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/gskj/rust-red-runtime-base:latest
          labels: rust-red-runtime-base
